### ISSUE TITLE
UI upgrade for ToDo-List App

### ISSUE THREAD

**Issue by dhirajbit** [n1snt/Simple-ToDo-List-Android#1]
Can I contribute to this project by upgrading its UI to Material 3?
This app is currently using Material 2 & I Would love to help migrate this app to Material 3.

**Comment by n1snt** [comment]
Please be my guest! good luck :-)

**Comment by n1snt** [comment]
Fixed in https://github.com/n1snt/Simple-ToDo-List-Android/pull/4
